-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateCommentRequiredArguments =
    { data : Api.InputObject.CommentInput }


{-| Create a new document in the collection of 'Comment'

  - data - 'Comment' input values

-}
createComment : CreateCommentRequiredArguments -> SelectionSet decodesTo Api.Object.Comment -> SelectionSet decodesTo RootMutation
createComment requiredArgs object_ =
    Object.selectionForCompositeField "createComment" [ Argument.required "data" requiredArgs.data Api.InputObject.encodeCommentInput ] object_ identity


type alias UpdateCommentRequiredArguments =
    { id : Api.ScalarCodecs.Id
    , data : Api.InputObject.CommentInput
    }


{-| Update an existing document in the collection of 'Comment'

  - id - The 'Comment' document's ID
  - data - 'Comment' input values

-}
updateComment : UpdateCommentRequiredArguments -> SelectionSet decodesTo Api.Object.Comment -> SelectionSet (Maybe decodesTo) RootMutation
updateComment requiredArgs object_ =
    Object.selectionForCompositeField "updateComment" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "data" requiredArgs.data Api.InputObject.encodeCommentInput ] object_ (identity >> Decode.nullable)


type alias DeleteCommentRequiredArguments =
    { id : Api.ScalarCodecs.Id }


{-| Delete an existing document in the collection of 'Comment'

  - id - The 'Comment' document's ID

-}
deleteComment : DeleteCommentRequiredArguments -> SelectionSet decodesTo Api.Object.Comment -> SelectionSet (Maybe decodesTo) RootMutation
deleteComment requiredArgs object_ =
    Object.selectionForCompositeField "deleteComment" [ Argument.required "id" requiredArgs.id (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object_ (identity >> Decode.nullable)
