-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.CommentPage exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The elements of type 'Comment' in this page.
-}
data : SelectionSet decodesTo Api.Object.Comment -> SelectionSet (List (Maybe decodesTo)) Api.Object.CommentPage
data object_ =
    Object.selectionForCompositeField "data" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| A cursor for elements coming after the current page.
-}
after : SelectionSet (Maybe String) Api.Object.CommentPage
after =
    Object.selectionForField "(Maybe String)" "after" [] (Decode.string |> Decode.nullable)


{-| A cursor for elements coming before the current page.
-}
before : SelectionSet (Maybe String) Api.Object.CommentPage
before =
    Object.selectionForField "(Maybe String)" "before" [] (Decode.string |> Decode.nullable)
